
# bottle
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word large  --mvtec_path='mvtec_data_path/ground_truth/bottle/broken_large/'  --log_folder "bottle_large"  > log_mvtec/bottle_large.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word small  --mvtec_path='mvtec_data_path/ground_truth/bottle/broken_small/'  --log_folder "bottle_small"  > log_mvtec/bottle_small.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word contamination  --mvtec_path='mvtec_data_path/ground_truth/bottle/contamination/' --log_folder "bottle_contamination"  > log_mvtec/bottle_contamination.log 2>&1 &

# hazelnut
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word crack  --mvtec_path='mvtec_data_path/hazelnut/ground_truth/crack/'  --log_folder "hazelnut_crack" > log_mvtec/hazelnut_crack.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word cut  --mvtec_path='mvtec_data_path/hazelnut/ground_truth/cut/'  --log_folder "hazelnut_cut" > log_mvtec/hazelnut_cut.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word hole  --mvtec_path='mvtec_data_path/hazelnut/ground_truth/hole/'  --log_folder "hazelnut_hole" > log_mvtec/hazelnut_hole.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word print  --mvtec_path='mvtec_data_path/hazelnut/ground_truth/print/'  --log_folder "hazelnut_print" > log_mvtec/hazelnut_print.log 2>&1 &


# toothbrush
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word defective  --mvtec_path='mvtec_data_path/toothbrush/ground_truth/defective/'  --log_folder "toothbrush_defective" > log_mvtec/toothbrush_defective.log 2>&1 &


# wood
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word color  --mvtec_path='mvtec_data_path/wood/ground_truth/color/'  --log_folder "wood_color" > log_mvtec/wood_color.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word hole  --mvtec_path='mvtec_data_path/wood/ground_truth/hole/'  --log_folder "wood_hole" > log_mvtec/wood_hole.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word liquid  --mvtec_path='mvtec_data_path/wood/ground_truth/liquid/'  --log_folder "wood_liquid" > log_mvtec/wood_liquid.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word combined  --mvtec_path='mvtec_data_path/wood/ground_truth/combined/'  --log_folder "wood_combined" > log_mvtec/wood_combined2.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word scratch  --mvtec_path='mvtec_data_path/wood/ground_truth/scratch/'  --log_folder "wood_scratch" > log_mvtec/wood_scratch.log 2>&1 &

# capsule
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word crack  --mvtec_path='mvtec_data_path/capsule/ground_truth/crack/'  --log_folder "capsule_crack" > log_mvtec/capsule_crack.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word imprint  --mvtec_path='mvtec_data_path/capsule/ground_truth/faulty_imprint/'  --log_folder "capsule_faulty_imprint" > log_mvtec/capsule_faulty_imprint.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word poke  --mvtec_path='mvtec_data_path/capsule/ground_truth/poke/'  --log_folder "capsule_poke" > log_mvtec/capsule_poke.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word scratch  --mvtec_path='mvtec_data_path/capsule/ground_truth/scratch/'  --log_folder "capsule_scratch" > log_mvtec/capsule_scratch.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word squeeze  --mvtec_path='mvtec_data_path/capsule/ground_truth/squeeze/'  --log_folder "capsule_squeeze" > log_mvtec/capsule_squeeze.log 2>&1 &

# transistor
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word bent  --mvtec_path='mvtec_data_path/transistor/ground_truth/bent_lead/'  --log_folder "transistor_bent_lead" > log_mvtec/transistor_bent_lead.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word cut  --mvtec_path='mvtec_data_path/transistor/ground_truth/cut_lead/'  --log_folder "transistor_cut_lead" > log_mvtec/transistor_cut_lead.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word damage  --mvtec_path='mvtec_data_path/transistor/ground_truth/damaged_case/'  --log_folder "transistor_demaged_case" > log_mvtec/transistor_damaged_case.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word miss  --mvtec_path='mvtec_data_path/transistor/ground_truth/misplaced/'  --log_folder "transistor_misplaced" > log_mvtec/transistor_misplaced.log 2>&1 &

# tile
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word crack  --mvtec_path='mvtec_data_path/tile/ground_truth/crack/'  --log_folder "tile_crack" > log_mvtec/tile_crack.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word strip  --mvtec_path='mvtec_data_path/tile/ground_truth/glue_strip/'  --log_folder "tile_glue_strip" > log_mvtec/tile_glue_strip.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word gray  --mvtec_path='mvtec_data_path/tile/ground_truth/gray_stroke/'  --log_folder "tile_gray_stroke" > log_mvtec/tile_gray_stroke.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word oil  --mvtec_path='mvtec_data_path/tile/ground_truth/oil/'  --log_folder "tile_oil" > log_mvtec/tile_oil.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word rough  --mvtec_path='mvtec_data_path/tile/ground_truth/rough/'  --log_folder "tile_rough" > log_mvtec/tile_rough.log 2>&1 &

# zipper
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word rough  --mvtec_path='mvtec_data_path/zipper/ground_truth/rough/'  --log_folder "zipper_rough" > log_mvtec/zipper_rough.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word broken  --mvtec_path='mvtec_data_path/zipper/ground_truth/broken_teeth/'  --log_folder "zipper_broken_teeth" > log_mvtec/zipper_broken_teeth.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word combined  --mvtec_path='mvtec_data_path/zipper/ground_truth/combined/'  --log_folder "zipper_combined" > log_mvtec/zipper_combined.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word border  --mvtec_path='mvtec_data_path/zipper/ground_truth/fabric_border/'  --log_folder "zipper_fabric_border" > log_mvtec/zipper_fabric_border.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word interior  --mvtec_path='mvtec_data_path/zipper/ground_truth/fabric_interior/'  --log_folder "zipper_fabric_interior" > log_mvtec/zipper_fabric_interior.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word split  --mvtec_path='mvtec_data_path/zipper/ground_truth/split_teeth/'  --log_folder "zipper_split_teeth" > log_mvtec/zipper_split_teeth.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word teeth  --mvtec_path='mvtec_data_path/zipper/ground_truth/squeezed_teeth/'  --log_folder "zipper_squeezed_teeth" > log_mvtec/zipper_squeezed_teeth.log 2>&1 &

# carpet
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word color  --mvtec_path='mvtec_data_path/carpet/ground_truth/color/'  --log_folder "carpet_color" > log_mvtec/carpet_color.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word thread  --mvtec_path='mvtec_data_path/carpet/ground_truth/thread/'  --log_folder "carpet_thread" > log_mvtec/carpet_thread.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word hole  --mvtec_path='mvtec_data_path/carpet/ground_truth/hole/'  --log_folder "carpet_hole" > log_mvtec/carpet_hole.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word cut  --mvtec_path='mvtec_data_path/carpet/ground_truth/cut/'  --log_folder "carpet_cut" > log_mvtec/carpet_cut.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word contamination  --mvtec_path='mvtec_data_path/carpet/ground_truth/metal_contamination/'  --log_folder "carpet_metal_contamination" > log_mvtec/carpet_metal_contamination.log 2>&1 &

# metal_nut
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word color  --mvtec_path='mvtec_data_path/metal_nut/ground_truth/color/'  --log_folder "metal_nut_color" > log_mvtec/metal_nut_color.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word bent  --mvtec_path='mvtec_data_path/metal_nut/ground_truth/bent/'  --log_folder "metal_nut_bent" > log_mvtec/metal_nut_bent.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word flip  --mvtec_path='mvtec_data_path/metal_nut/ground_truth/flip/'  --log_folder "metal_nut_flip" > log_mvtec/metal_nut_flip.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word scratch  --mvtec_path='mvtec_data_path/metal_nut/ground_truth/scratch/'  --log_folder "metal_nut_scratch" > log_mvtec/metal_nut_scratch.log 2>&1 &


# grid
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word grid  --mvtec_path='mvtec_data_path/grid/ground_truth/broken/'  --log_folder "grid_broken" > log_mvtec/grid_broken.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word glue  --mvtec_path='mvtec_data_path/grid/ground_truth/glue/'  --log_folder "grid_glue" > log_mvtec/grid_glue.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word bent  --mvtec_path='mvtec_data_path/grid/ground_truth/bent/'  --log_folder "grid_bent" > log_mvtec/grid_bent.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word thread  --mvtec_path='mvtec_data_path/grid/ground_truth/thread/'  --log_folder "grid_thread" > log_mvtec/grid_thread.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word contamination  --mvtec_path='mvtec_data_path/grid/ground_truth/metal_contamination/'  --log_folder "grid_contamination" > log_mvtec/grid_contamination.log 2>&1 &


# screw
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word front  --mvtec_path='mvtec_data_path/screw/ground_truth/manipulated_front/'  --log_folder "screw_manipulated_front" > log_mvtec/screw_manipulated_front.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word head  --mvtec_path='mvtec_data_path/screw/ground_truth/scratch_head/'  --log_folder "screw_scratch_head" > log_mvtec/screw_scratch_head.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word neck  --mvtec_path='mvtec_data_path/screw/ground_truth/scratch_neck/'  --log_folder "screw_scratch_neck" > log_mvtec/screw_scratch_neck.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word side  --mvtec_path='mvtec_data_path/screw/ground_truth/thread_side/'  --log_folder "screw_thread_side" > log_mvtec/screw_thread_side.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word top  --mvtec_path='mvtec_data_path/screw/ground_truth/thread_top/'  --log_folder "screw_thread_top" > log_mvtec/screw_thread_top.log 2>&1 &

# cable
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word wire  --mvtec_path='mvtec_data_path/cable/ground_truth/bent_wire/'  --log_folder "cable_bent_wire" > log_mvtec/cable_bent_wire.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word swap  --mvtec_path='mvtec_data_path/cable/ground_truth/cable_swap/'  --log_folder "cable_swap" > log_mvtec/cable_swap.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word combined  --mvtec_path='mvtec_data_path/cable/ground_truth/combined/'  --log_folder "cable_combined" > log_mvtec/cable_combined.log 2>&1 &

nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word cut  --mvtec_path='mvtec_data_path/cable/ground_truth/cut_inner_insulation/'  --log_folder "cable_cut_inner_insulation" > log_mvtec/cable_cut_inner_insulation.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word cut  --mvtec_path='mvtec_data_path/cable/ground_truth/cut_outer_insulation/'  --log_folder "cable_cut_outer_insulation" > log_mvtec/cable_cut_outer_insulation.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word miss  --mvtec_path='mvtec_data_path/cable/ground_truth/missing_cable/'  --log_folder "cable_missing_cable" > log_mvtec/cable_missing_cable.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 3, --init_word miss  --mvtec_path='mvtec_data_path/cable/ground_truth/missing_wire/'  --log_folder "cable_missing_wire" > log_mvtec/cable_missing_wire.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word poke  --mvtec_path='mvtec_data_path/cable/ground_truth/poke_insulation/'  --log_folder "cable_poke_insulation"  > log_mvtec/cable_poke_insulation.log 2>&1 &


# leather
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word color  --mvtec_path='mvtec_data_path/leather/ground_truth/color/'  --log_folder "leather_color" > log_mvtec/leather_color.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word cut  --mvtec_path='mvtec_data_path/leather/ground_truth/cut/'  --log_folder "leather_cut" > log_mvtec/leather_cut.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0, --init_word fold  --mvtec_path='mvtec_data_path/leather/ground_truth/fold/'  --log_folder "leather_fold" > log_mvtec/leather_fold.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 1, --init_word glue  --mvtec_path='mvtec_data_path/leather/ground_truth/glue/'  --log_folder "leather_glue" > log_mvtec/leather_glue.log 2>&1 &
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word poke  --mvtec_path='mvtec_data_path/leather/ground_truth/poke/'  --log_folder "leather_poke" > log_mvtec/leather_poke.log 2>&1 &


# pill
nohup python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder-mvtex.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 2, --init_word pill  --mvtec_path='mvtec_data_path/pill/ground_truth/pill_type/'  --log_folder "pill_type" > log_mvtec/pill_type.log 2>&1 &


# bottle
CUDA_VISIBLE_DEVICES=3 python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 53999 --init_word large --anomaly_name='bottle_large' --pt_path='logs/bottle_large/checkpoints/' --mask_path='mvtec_data_path/ground_truth/broken_large/'
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 59999 --init_word small --anomaly_name='bottle_small' --pt_path='logs/bottle_small/checkpoints/' --mask_path='mvtec_data_path/ground_truth/broken_small/'
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 55999 --init_word contamination --anomaly_name='bottle_contamination' --pt_path='logs/bottle_contamination/checkpoints/' --mask_path='mvtec_data_path/ground_truth/contamination/'

CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 53999 --init_word large --anomaly_name='bottle_large' --pt_path='logs/bottle_large/checkpoints/' --mask_path='mvtec_data_path/ground_truth/broken_large/' > gen/bottle_large.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 59999 --init_word small --anomaly_name='bottle_small' --pt_path='logs/bottle_small/checkpoints/' --mask_path='mvtec_data_path/ground_truth/broken_small/' > gen/bottle_small.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/train/good/' --sample_name='bottle_8002' --weight_idx 55999 --init_word contamination --anomaly_name='bottle_contamination' --pt_path='logs/bottle_contamination/checkpoints/' --mask_path='mvtec_data_path/ground_truth/contamination/'  > gen/bottle_contamination.log 2>&1 &



# hazelnut
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --sample_name='ddpm_mask' --weight_idx 45999 --init_word hole --anomaly_name='hazelnut_hole' --pt_path='logs/hazelnut_hole/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/hole/'
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --sample_name='ddpm_mask' --weight_idx 57999 --init_word print --anomaly_name='hazelnut_print' --pt_path='logs/hazelnut_print/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/print/'
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --sample_name='ddpm_mask' --weight_idx 47999 --init_word cut --anomaly_name='hazelnut_cut' --pt_path='logs/hazelnut_cut/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/cut/'
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --sample_name='ddpm_mask' --weight_idx 51999 --init_word crack --anomaly_name='hazelnut_crack' --pt_path='logs/hazelnut_crack/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/crack/'


CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --weight_idx 49999 --sample_name='hazelnut_8002' --init_word crack --anomaly_name='hazelnut_crack' --pt_path='logs/hazelnut_crack/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/crack/' > gen/hazelnut_crack.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --weight_idx 45999 --sample_name='hazelnut_8002' --init_word hole --anomaly_name='hazelnut_hole' --pt_path='logs/hazelnut_hole/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/hole/' > gen/hazelnut_hole.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --weight_idx 57999 --sample_name='hazelnut_8002' --init_word print --anomaly_name='hazelnut_print' --pt_path='logs/hazelnut_print/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/print/' > gen/hazelnut_print.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --weight_idx 47999 --sample_name='hazelnut_8002' --init_word cut --anomaly_name='hazelnut_cut' --pt_path='logs/hazelnut_cut/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/cut/' > gen/hazelnut_cut.log 2>&1 &



python generate_with_mask_mvtec.py --data_root='mvtec_data_path/hazelnut/train/good/' --sample_name='hazelnut' --init_word cut --anomaly_name='hazelnut_cut' --pt_path='logs/hazelnut_cut/checkpoints/' --mask_path='mvtec_data_path/hazelnut/ground_truth/cut/'

# toothbrush
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/toothbrush/train/good/' --weight_idx 63999 --sample_name='toothbrush_8002' --init_word defective --anomaly_name='toothbrush_defective' --pt_path='logs/toothbrush_defective/checkpoints/' --mask_path='mvtec_data_path/toothbrush/ground_truth/defective/' > gen/toothbrush_defective.log 2>&1 &

# wood
CUDA_VISIBLE_DEVICES=3  python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 53999 --sample_name='wood_8002' --init_word color --anomaly_name='wood_color' --pt_path='logs/wood_color/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/color/'

CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 53999 --sample_name='wood_8002' --init_word color --anomaly_name='wood_color' --pt_path='logs/wood_color/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/color/' > gen/wood_color.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 51999 --sample_name='wood_8002' --init_word combined --anomaly_name='wood_combined' --pt_path='logs/wood_combined/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/combined/' > gen/wood_combined.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 49999 --sample_name='wood_8002' --init_word hole --anomaly_name='wood_hole' --pt_path='logs/wood_hole/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/hole/' > gen/wood_hole.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 61999 --sample_name='wood_8002' --init_word liquid --anomaly_name='wood_liquid' --pt_path='logs/wood_liquid/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/liquid/' > gen/wood_liquid.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/wood/train/good/' --weight_idx 43999 --sample_name='wood_8002' --init_word scratch --anomaly_name='wood_scratch' --pt_path='logs/wood_scratch/checkpoints/' --mask_path='mvtec_data_path/wood/ground_truth/scratch/' > gen/wood_scratch.log 2>&1 &

# transistor
CUDA_VISIBLE_DEVICES=2 python generate_with_mask_mvtec.py --data_root='mvtec_data_path/transistor/train/good/' --weight_idx 49999 --sample_name='transistor_8002' --init_word bent --anomaly_name='transistor_bent_lead' --pt_path='logs/transistor_bent_lead/checkpoints/' --mask_path='mvtec_data_path/transistor/ground_truth/bent_lead/' 
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/transistor/train/good/' --weight_idx 61999 --sample_name='transistor_8002' --init_word bent --anomaly_name='transistor_bent_lead' --pt_path='logs/transistor_bent_lead/checkpoints/' --mask_path='mvtec_data_path/transistor/ground_truth/bent_lead/' > gen/transistor_bent_lead.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/transistor/train/good/' --weight_idx 51999 --sample_name='transistor_8002' --init_word cut --anomaly_name='transistor_cut_lead' --pt_path='logs/transistor_cut_lead/checkpoints/' --mask_path='mvtec_data_path/transistor/ground_truth/cut_lead/' > gen/transistor_cut_lead.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/transistor/train/good/' --weight_idx 97999 --sample_name='transistor_8002' --init_word damage --anomaly_name='transistor_damaged_case' --pt_path='logs/transistor_damaged_case/checkpoints/' --mask_path='mvtec_data_path/transistor/ground_truth/damaged_case/' > gen/transistor_damaged_case.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/transistor/train/good/' --weight_idx 63999 --sample_name='transistor_8002' --init_word miss --anomaly_name='transistor_misplaced' --pt_path='logs/transistor_misplaced/checkpoints/' --mask_path='mvtec_data_path/transistor/ground_truth/misplaced/' > gen/transistor_misplaced.log 2>&1 &

# tile
CUDA_VISIBLE_DEVICES=2 python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 55999 --sample_name='tile_8002' --init_word crack --anomaly_name='tile_crack' --pt_path='logs/tile_crack/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/crack/'
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 55999 --sample_name='tile_8002' --init_word crack --anomaly_name='tile_crack' --pt_path='logs/tile_crack/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/crack/' > gen/tile_crack.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 57999 --sample_name='tile_8002' --init_word strip --anomaly_name='tile_glue_strip' --pt_path='logs/tile_glue_strip/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/glue_strip/' > gen/tile_glue_strip.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 57999 --sample_name='tile_8002' --init_word gray --anomaly_name='tile_gray_stroke' --pt_path='logs/tile_gray_stroke/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/gray_stroke/' > gen/tile_gray_stroke.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 51999 --sample_name='tile_8002' --init_word oil --anomaly_name='tile_oil' --pt_path='logs/tile_oil/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/oil/' > gen/tile_oil.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/tile/train/good/' --weight_idx 49999 --sample_name='tile_8002' --init_word rough --anomaly_name='tile_rough' --pt_path='logs/tile_rough/checkpoints/' --mask_path='mvtec_data_path/tile/ground_truth/rough/' > gen/tile_rough.log 2>&1 &


# capsule

CUDA_VISIBLE_DEVICES=1 python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 57999 --sample_name='capsule_8002' --init_word crack --anomaly_name='capsule_crack' --pt_path='logs/capsule_crack/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/crack/'
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 57999 --sample_name='capsule_8002' --init_word crack --anomaly_name='capsule_crack' --pt_path='logs/capsule_crack/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/crack/' > gen/capsule_crack.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 59999 --sample_name='capsule_8002' --init_word imprint --anomaly_name='capsule_faulty_imprint' --pt_path='logs/capsule_faulty_imprint/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/faulty_imprint/' > gen/capsule_faulty_imprint.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 53999 --sample_name='capsule_8002' --init_word poke --anomaly_name='capsule_poke' --pt_path='logs/capsule_poke/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/poke/' > gen/capsule_poke.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 53999 --sample_name='capsule_8002' --init_word scratch --anomaly_name='capsule_scratch' --pt_path='logs/capsule_scratch/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/scratch/' > gen/capsule_scratch.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/capsule/train/good/' --weight_idx 53999 --sample_name='capsule_8002' --init_word squeeze --anomaly_name='capsule_squeeze' --pt_path='logs/capsule_squeeze/checkpoints/' --mask_path='mvtec_data_path/capsule/ground_truth/squeeze/' > gen/capsule_squeeze.log 2>&1 &


# metal_nut
CUDA_VISIBLE_DEVICES=1 python generate_with_mask_mvtec.py --data_root='mvtec_data_path/metal_nut/train/good/' --weight_idx 57999 --sample_name='metal_nut_8002' --init_word color --anomaly_name='metal_nut_color' --pt_path='logs/metal_nut_color/checkpoints/' --mask_path='mvtec_data_path/metal_nut/ground_truth/color/'
CUDA_VISIBLE_DEVICES=0 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/metal_nut/train/good/' --weight_idx 57999 --sample_name='metal_nut_8002' --init_word color --anomaly_name='metal_nut_color' --pt_path='logs/metal_nut_color/checkpoints/' --mask_path='mvtec_data_path/metal_nut/ground_truth/color/' > gen/metal_nut_color.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/metal_nut/train/good/' --weight_idx 67999 --sample_name='metal_nut_8002' --init_word bent --anomaly_name='metal_nut_bent' --pt_path='logs/metal_nut_bent/checkpoints/' --mask_path='mvtec_data_path/metal_nut/ground_truth/bent/' > gen/metal_nut_bent.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/metal_nut/train/good/' --weight_idx 47999 --sample_name='metal_nut_8002' --init_word flip --anomaly_name='metal_nut_flip' --pt_path='logs/metal_nut_flip/checkpoints/' --mask_path='mvtec_data_path/metal_nut/ground_truth/flip/' > gen/metal_nut_flip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/metal_nut/train/good/' --weight_idx 71999 --sample_name='metal_nut_8002' --init_word scratch --anomaly_name='metal_nut_scratch' --pt_path='logs/metal_nut_scratch/checkpoints/' --mask_path='mvtec_data_path/metal_nut/ground_truth/scratch/' > gen/metal_nut_scratch.log 2>&1 &


# zipper
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 59999 --sample_name='zipper_8002' --init_word rough --anomaly_name='zipper_rough' --pt_path='logs/zipper_rough/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/rough/'  > gen/zipper_rough.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 61999 --sample_name='zipper_8002' --init_word broken --anomaly_name='zipper_broken_teeth' --pt_path='logs/zipper_broken_teeth/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/broken_teeth/'  > gen/zipper_broken_teeth.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 49999 --sample_name='zipper_8002' --init_word combined --anomaly_name='zipper_combined' --pt_path='logs/zipper_combined/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/combined/'  > gen/zipper_combined.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 59999 --sample_name='zipper_8002' --init_word border --anomaly_name='zipper_fabric_border' --pt_path='logs/zipper_fabric_border/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/fabric_border/'  > gen/zipper_fabric_border.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 57999 --sample_name='zipper_8002' --init_word interior --anomaly_name='zipper_fabric_interior' --pt_path='logs/zipper_fabric_interior/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/fabric_interior/'  > gen/zipper_fabric_interior.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 55999 --sample_name='zipper_8002' --init_word split --anomaly_name='zipper_split_teeth' --pt_path='logs/zipper_split_teeth/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/split_teeth/'  > gen/zipper_split_teeth.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/zipper/train/good/' --weight_idx 59999 --sample_name='zipper_8002' --init_word teeth --anomaly_name='zipper_squeezed_teeth' --pt_path='logs/zipper_squeezed_teeth/checkpoints/' --mask_path='mvtec_data_path/zipper/ground_truth/squeezed_teeth/'  > gen/zipper_squeezed_teeth.log 2>&1 &


# leather
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 58499 --sample_name='leather_8002' --init_word color --anomaly_name='leather_color' --pt_path='logs/leather_color/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/color/'
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 56999 --sample_name='leather_8002' --init_word color --anomaly_name='leather_color' --pt_path='logs/leather_color/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/color/'  > gen/leather_color.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 52499 --sample_name='leather_8002' --init_word cut --anomaly_name='leather_cut' --pt_path='logs/leather_cut/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/cut/'  > gen/leather_cut.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 58499 --sample_name='leather_8002' --init_word fold --anomaly_name='leather_fold' --pt_path='logs/leather_fold/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/fold/'  > gen/leather_fold.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 53999 --sample_name='leather_8002' --init_word glue --anomaly_name='leather_glue' --pt_path='logs/leather_glue/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/glue/'  > gen/leather_glue.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/leather/train/good/' --weight_idx 55499 --sample_name='leather_8002' --init_word poke --anomaly_name='leather_poke' --pt_path='logs/leather_poke/checkpoints/' --mask_path='mvtec_data_path/leather/ground_truth/poke/'  > gen/leather_poke.log 2>&1 &



# carpet
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 59999 --sample_name='carpet_8002' --init_word color --anomaly_name='carpet_color' --pt_path='logs/carpet_color/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/color/'

nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 53999 --sample_name='carpet_8002' --init_word color --anomaly_name='carpet_color' --pt_path='logs/carpet_color/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/color/' > gen/carpet_color.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 69999 --sample_name='carpet_8002' --init_word thread --anomaly_name='carpet_thread' --pt_path='logs/carpet_thread/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/thread/' > gen/carpet_thread.log 2>&1 &
nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 57999 --sample_name='carpet_8002' --init_word hole --anomaly_name='carpet_hole' --pt_path='logs/carpet_hole/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/hole/' > gen/carpet_hole.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 59999 --sample_name='carpet_8002' --init_word cut --anomaly_name='carpet_cut' --pt_path='logs/carpet_cut/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/cut/' > gen/carpet_cut.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/carpet/train/good/' --weight_idx 59999 --sample_name='carpet_8002' --init_word contamination --anomaly_name='carpet_metal_contamination' --pt_path='logs/carpet_metal_contamination/checkpoints/' --mask_path='mvtec_data_path/carpet/ground_truth/metal_contamination/' > gen/carpet_metal_contamination.log 2>&1 &


# grid
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 53999 --sample_name='grid_8002' --init_word grid --anomaly_name='grid_broken' --pt_path='logs/grid_broken/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/broken/'
nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 53999 --sample_name='grid_8002' --init_word grid --anomaly_name='grid_broken' --pt_path='logs/grid_broken/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/broken/' > gen/grid_broken.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 63999 --sample_name='grid_8002' --init_word glue --anomaly_name='grid_glue' --pt_path='logs/grid_glue/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/glue/' > gen/grid_glue.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 55999 --sample_name='grid_8002' --init_word bent --anomaly_name='grid_bent' --pt_path='logs/grid_bent/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/bent/' > gen/grid_bent.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 65999 --sample_name='grid_8002' --init_word thread --anomaly_name='grid_thread' --pt_path='logs/grid_thread/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/thread/' > gen/grid_thread.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/grid/train/good/' --weight_idx 59999 --sample_name='grid_8002' --init_word contamination --anomaly_name='grid_contamination' --pt_path='logs/grid_contamination/checkpoints/' --mask_path='mvtec_data_path/grid/ground_truth/metal_contamination/' > gen/grid_contamination.log 2>&1 &


# cable

python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 55999 --sample_name='cable_8002' --init_word wire --anomaly_name='cable_bent_wire' --pt_path='logs/cable_bent_wire/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/bent_wire/'
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 55999 --sample_name='cable_8002' --init_word wire --anomaly_name='cable_bent_wire' --pt_path='logs/cable_bent_wire/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/bent_wire/'  > gen/cable_bent_wire.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 59999 --sample_name='cable_8002' --init_word swap --anomaly_name='cable_swap' --pt_path='logs/cable_swap/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/cable_swap/'  > gen/cable_swap.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 53999 --sample_name='cable_8002' --init_word combined --anomaly_name='cable_combined' --pt_path='logs/cable_combined/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/combined/'  > gen/cable_combined.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 61499 --sample_name='cable_8002' --init_word cut --anomaly_name='cable_cut_inner_insulation' --pt_path='logs/cable_cut_inner_insulation/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/cut_inner_insulation/'  > gen/cable_cut_inner_insulation.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 55499 --sample_name='cable_8002' --init_word cut --anomaly_name='cable_cut_outer_insulation' --pt_path='logs/cable_cut_outer_insulation/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/cut_outer_insulation/'  > gen/cable_cut_outer_insulation.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 56999 --sample_name='cable_8002' --init_word miss --anomaly_name='cable_missing_cable' --pt_path='logs/cable_missing_cable/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/missing_cable/'  > gen/cable_missing_cable.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 56999 --sample_name='cable_8002' --init_word miss --anomaly_name='cable_missing_wire' --pt_path='logs/cable_missing_wire/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/missing_wire/'  > gen/cable_missing_wire.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/cable/train/good/' --weight_idx 62999 --sample_name='cable_8002' --init_word poke --anomaly_name='cable_poke_insulation' --pt_path='logs/cable_poke_insulation/checkpoints/' --mask_path='mvtec_data_path/cable/ground_truth/poke_insulation/'  > gen/cable_poke_insulation.log 2>&1 &



# screw
python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 55999 --sample_name='screw_8002' --init_word front --anomaly_name='screw_manipulated_front' --pt_path='logs/screw_manipulated_front/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/manipulated_front/'
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 55999 --sample_name='screw_8002' --init_word front --anomaly_name='screw_manipulated_front' --pt_path='logs/screw_manipulated_front/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/manipulated_front/'  > gen/screw_manipulated_front.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 57999 --sample_name='screw_8002' --init_word head --anomaly_name='screw_scratch_head' --pt_path='logs/screw_scratch_head/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/scratch_head/'  > gen/screw_scratch_head.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 53999 --sample_name='screw_8002' --init_word neck --anomaly_name='screw_scratch_neck' --pt_path='logs/screw_scratch_neck/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/scratch_neck/'  > gen/screw_scratch_neck.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 51999 --sample_name='screw_8002' --init_word side --anomaly_name='screw_thread_side' --pt_path='logs/screw_thread_side/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/thread_side/'  > gen/screw_thread_side.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python generate_with_mask_mvtec.py --data_root='mvtec_data_path/screw/train/good/' --weight_idx 57999 --sample_name='screw_8002' --init_word top --anomaly_name='screw_thread_top' --pt_path='logs/screw_thread_top/checkpoints/' --mask_path='mvtec_data_path/screw/ground_truth/thread_top/'  > gen/screw_thread_top.log 2>&1 &


